<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Ngoyarez',
                'email' => 'cj@cj.com',
                'code' => 'XOK0OZRMKW',
                'username' => 'cj',
                'user_type' => 'super_admin',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost:8001/storage/uploads/super_admin/XOK0OZRMKW/photo.jpeg',
                'phone' => '+254748883944',
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => 'Nairobi, Kenya',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QvvIUwKDjBM9IDKSwrvpZuUSYB2uo1HZ2G.IIz.jJwdGk8OD3ptrC',
                'remember_token' => 'TcxBbU9C2Z35HnE5l279Am9a6cbTR8BmBlJPZdTjmYcjbBl4Y3E6FfGUZzd0',
                'created_at' => NULL,
                'updated_at' => '2024-06-24 14:44:18',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Admin KORA',
                'email' => 'admin@admin.com',
                'code' => '9LGABMZGQQ',
                'username' => 'admin',
                'user_type' => 'admin',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QvvIUwKDjBM9IDKSwrvpZuUSYB2uo1HZ2G.IIz.jJwdGk8OD3ptrC',
                'remember_token' => 'CBjo1Rm5639dUvnjM9ftrJLavg2VdyeS43SYvtlSnaeAtCLlQwqaweyN9CUa',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Teacher Chike',
                'email' => 'teacher@teacher.com',
                'code' => 'UN8DORKTTI',
                'username' => 'teacher',
                'user_type' => 'teacher',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QvvIUwKDjBM9IDKSwrvpZuUSYB2uo1HZ2G.IIz.jJwdGk8OD3ptrC',
                'remember_token' => 'vspFtkwy9Ab9AwA0Vv8aMjjyZTgtfdeH0hg53TO5I8fkNGWOMKm1f0TzvwUP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Parent Kaba',
                'email' => 'parent@parent.com',
                'code' => 'LRG01R2ZWC',
                'username' => 'parent',
                'user_type' => 'parent',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QvvIUwKDjBM9IDKSwrvpZuUSYB2uo1HZ2G.IIz.jJwdGk8OD3ptrC',
                'remember_token' => 'OkcB85qI4xJtQxUGxxtATgx4Pevk0XAAQkwJSlcediMHNiJp5JuPlKpvPJPa',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Accountant Jeff',
                'email' => 'accountant@accountant.com',
                'code' => 'MAVTLYXARP',
                'username' => 'accountant',
                'user_type' => 'accountant',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QvvIUwKDjBM9IDKSwrvpZuUSYB2uo1HZ2G.IIz.jJwdGk8OD3ptrC',
                'remember_token' => 'wJVMOCpTESajq6aaY9FZ3cfvNVymw4a0XdIpWUoqghS7FGSdNVjIp9OKsI2L',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Admin 1',
                'email' => 'admin1@admin.com',
                'code' => '6TJVDPH9RM',
                'username' => 'admin1',
                'user_type' => 'admin',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QPtIj.jQCXp3/NoFN7.VIe782/ur51jsP2DBRM9kfoOkYu568UYWG',
                'remember_token' => 'IbbZbDLpq3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Teacher 1',
                'email' => 'teacher1@teacher.com',
                'code' => '8YTX1CPDPX',
                'username' => 'teacher1',
                'user_type' => 'teacher',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$NdoAclcIgs4GUHiobs1eK.KywhZhLHLRo3n0eAc.K5gm71HStJ5VK',
                'remember_token' => 'A5PbHyV1NN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Accountant 1',
                'email' => 'accountant1@accountant.com',
                'code' => '8FULTUQSN4',
                'username' => 'accountant1',
                'user_type' => 'accountant',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$SH95s2xeRKUmK/dJgl66T.617e8/0YIv7Cuuq7N29bH4tQGRBNUFS',
                'remember_token' => 'EevIMBQXcD',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Parent 1',
                'email' => 'parent1@parent.com',
                'code' => 'FJW105SNHM',
                'username' => 'parent1',
                'user_type' => 'parent',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$MT8flFTMbPLKRvqJqED7EeAj.iUz4/RQsKhl6zZgHoxkik9uEvDB.',
                'remember_token' => '6suoX43GRE',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Admin 2',
                'email' => 'admin2@admin.com',
                'code' => 'R6R8ZFQ1CC',
                'username' => 'admin2',
                'user_type' => 'admin',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QQJ2OTYMfSIwKCLCjclrw.KzqvfVd.dzIeW6qKGAoDK0Ui.w3zhdy',
                'remember_token' => 'VplGVCJUOB',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Teacher 2',
                'email' => 'teacher2@teacher.com',
                'code' => 'R3JWAWAPBM',
                'username' => 'teacher2',
                'user_type' => 'teacher',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$o/kYE29a4iCrMn9hwxgFaOWK.CDCulHDYBZv6YECORyGypQ0EqjJm',
                'remember_token' => '6fUm3z7VAb',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Accountant 2',
                'email' => 'accountant2@accountant.com',
                'code' => 'YWJ2WT1JUT',
                'username' => 'accountant2',
                'user_type' => 'accountant',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$U7HDg3PTGBomViGQ/L6Oue4SKdD89OD0W0RqHvbuKQxrwjky9.bkG',
                'remember_token' => 'kSuzrDIlcH',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Parent 2',
                'email' => 'parent2@parent.com',
                'code' => 'PZNDM1FTLV',
                'username' => 'parent2',
                'user_type' => 'parent',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Ji8MZSG1qTCMc4yXydhOvOSv8kMWz5g2KfJMPd6h0WSns6czHSUEu',
                'remember_token' => '4Ac35eU4YW',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Admin 3',
                'email' => 'admin3@admin.com',
                'code' => 'RUE31KPRUN',
                'username' => 'admin3',
                'user_type' => 'admin',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$qA9/qBAfhr9V6pOE8ZsX.usKdEqhIhVt//X868xVCa0cQxZAw9wcu',
                'remember_token' => 'FQa1lnSqOc',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Teacher 3',
                'email' => 'teacher3@teacher.com',
                'code' => 'OUHSYNMVCI',
                'username' => 'teacher3',
                'user_type' => 'teacher',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Zke6YKyZSGzEpgQLde42ieEEeuxgA5TXMbHX78rngWwQ0JgwnBl66',
                'remember_token' => 'XUavG5TmXO',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Accountant 3',
                'email' => 'accountant3@accountant.com',
                'code' => '96ORVQOJ0F',
                'username' => 'accountant3',
                'user_type' => 'accountant',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$askOYdPwEaqjsHPpH2jWE.dwrD4e2Vb9sqUmsSSjLtTK4LpppnJA6',
                'remember_token' => 'czQXdG1yju',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Parent 3',
                'email' => 'parent3@parent.com',
                'code' => 'FRIO9NTOMP',
                'username' => 'parent3',
                'user_type' => 'parent',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$h8rINeQjeJkgQzywTzI65OZaHUaWZEkGvbLzaCm2zdWKcgHjZzlGW',
                'remember_token' => 'Mya7qcwekM',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Student CJ',
                'email' => 'student@student.com',
                'code' => 'N9BO151F7G',
                'username' => 'student',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4Jk.JzEOSA5D4WWgvBTU9eAiloUGwoHMGq0OjZytilrh7Iqmx/4Dq',
                'remember_token' => 'uyfbK1jP2niAozjjwVCapNTrG96g8JgVIbpHdZH6Vi9ypzQAKzJCw5fCJh4x',
                'created_at' => '2024-06-24 10:40:52',
                'updated_at' => '2024-06-24 10:40:52',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Casper Bednar',
                'email' => 'bwyman@example.com',
                'code' => 'FSLTYUTSHY',
                'username' => 'kshlerin.kayley',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Q/L8OWNPyQLBKLgTp0HcRe5.DlSGNLMeua4t7Mvj5hO0jFMEnhJjK',
                'remember_token' => 'Zqm4qBGSUs',
                'created_at' => '2024-06-24 10:40:52',
                'updated_at' => '2024-06-24 10:40:52',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Grace Cole',
                'email' => 'jzulauf@example.org',
                'code' => '97ZUBEXI9F',
                'username' => 'muriel.hagenes',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Q/L8OWNPyQLBKLgTp0HcRe5.DlSGNLMeua4t7Mvj5hO0jFMEnhJjK',
                'remember_token' => 'OrrCUZzl4J',
                'created_at' => '2024-06-24 10:40:52',
                'updated_at' => '2024-06-24 10:40:52',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Loyce Kub',
                'email' => 'osvaldo.kshlerin@example.net',
                'code' => 'KKLQLHPTJS',
                'username' => 'prince84',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Q/L8OWNPyQLBKLgTp0HcRe5.DlSGNLMeua4t7Mvj5hO0jFMEnhJjK',
                'remember_token' => 'PKqaGbuBcC',
                'created_at' => '2024-06-24 10:40:52',
                'updated_at' => '2024-06-24 10:40:52',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Prof. Delfina Schamberger DDS',
                'email' => 'marcelino.robel@example.net',
                'code' => 'GHOUT3SBCP',
                'username' => 'meta.howe',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$No5e6IWU.RNIFnWbP3643O0BOqCbR4SkcmeXwFrlF1QQ5XajyCuka',
                'remember_token' => '0VIbZe7gQi',
                'created_at' => '2024-06-24 10:40:53',
                'updated_at' => '2024-06-24 10:40:53',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Chris Schimmel',
                'email' => 'tvolkman@example.org',
                'code' => '7IVXPXAKB4',
                'username' => 'kaleb.kohler',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$No5e6IWU.RNIFnWbP3643O0BOqCbR4SkcmeXwFrlF1QQ5XajyCuka',
                'remember_token' => 'sxAXTRppki',
                'created_at' => '2024-06-24 10:40:53',
                'updated_at' => '2024-06-24 10:40:53',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Prof. Keaton Hahn',
                'email' => 'tony.olson@example.org',
                'code' => 'D79B1H9T0K',
                'username' => 'daija58',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$No5e6IWU.RNIFnWbP3643O0BOqCbR4SkcmeXwFrlF1QQ5XajyCuka',
                'remember_token' => 'Da2S2s0qC6',
                'created_at' => '2024-06-24 10:40:53',
                'updated_at' => '2024-06-24 10:40:53',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Mr. Cicero Gleichner',
                'email' => 'eerdman@example.net',
                'code' => 'Z6TZ3GKQ1T',
                'username' => 'gorczany.keara',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4/OCpawbaFgaweZaKPesqOoYznsMLGJ0Z2P7pYin7q0hFMJRvvOVW',
                'remember_token' => 'hnwTmDYfAg',
                'created_at' => '2024-06-24 10:40:53',
                'updated_at' => '2024-06-24 10:40:53',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Orin Rempel II',
                'email' => 'wehner.jules@example.org',
                'code' => 'AHPCLIHC3Q',
                'username' => 'cielo10',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4/OCpawbaFgaweZaKPesqOoYznsMLGJ0Z2P7pYin7q0hFMJRvvOVW',
                'remember_token' => 'oUlqutqnCC',
                'created_at' => '2024-06-24 10:40:53',
                'updated_at' => '2024-06-24 10:40:53',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Dr. Kailyn Lehner Jr.',
                'email' => 'yost.kathleen@example.net',
                'code' => 'UVL4LEBXMW',
                'username' => 'marina.kohler',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4/OCpawbaFgaweZaKPesqOoYznsMLGJ0Z2P7pYin7q0hFMJRvvOVW',
                'remember_token' => 'WQS5GgPYtP',
                'created_at' => '2024-06-24 10:40:53',
                'updated_at' => '2024-06-24 10:40:53',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Keyshawn McCullough',
                'email' => 'herta.fisher@example.org',
                'code' => 'GLDUACSZPH',
                'username' => 'stiedemann.enid',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$3WJ9ZLptR4npqXSdipVcFOh3KsVareeKm9zT7IkNnVo65A0rLEAtS',
                'remember_token' => 'ogfXQjLCqR',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Howell Powlowski',
                'email' => 'chester.johnston@example.net',
                'code' => 'SWIXEHF4RN',
                'username' => 'auer.dereck',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$3WJ9ZLptR4npqXSdipVcFOh3KsVareeKm9zT7IkNnVo65A0rLEAtS',
                'remember_token' => '2DWFKqEf33',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Edd Harris',
                'email' => 'gkoch@example.net',
                'code' => '0CPGEAPMHS',
                'username' => 'reina70',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$3WJ9ZLptR4npqXSdipVcFOh3KsVareeKm9zT7IkNnVo65A0rLEAtS',
                'remember_token' => 'U2nYpIProf',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Prof. Maya Kemmer V',
                'email' => 'pietro.waelchi@example.org',
                'code' => 'OTDTNBHJ8F',
                'username' => 'norene03',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$eRCJ4wHWw9BRsIZ80wib5.yzgdv7VnSqWCQJVn.DuVZ3MpVAH/5yW',
                'remember_token' => 'p3NqwhNE8Q',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Julian Glover',
                'email' => 'garfield.gottlieb@example.com',
                'code' => 'KBHBFSWAP8',
                'username' => 'amelie.durgan',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$eRCJ4wHWw9BRsIZ80wib5.yzgdv7VnSqWCQJVn.DuVZ3MpVAH/5yW',
                'remember_token' => '4lJdJ9Jiep',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Dexter Schroeder',
                'email' => 'amely78@example.net',
                'code' => 'LQYP1V66PN',
                'username' => 'bergnaum.gladyce',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$eRCJ4wHWw9BRsIZ80wib5.yzgdv7VnSqWCQJVn.DuVZ3MpVAH/5yW',
                'remember_token' => 'fpPPsE8GxH',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Yvonne Kuhn',
                'email' => 'grimes.frederique@example.org',
                'code' => 'CDXV1RXLDT',
                'username' => 'syble53',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Jqy6Z0hIwLdK6KEnwQQnauCBwATGX7hKOTREIt14pzOs/mAnan2ee',
                'remember_token' => 'rMd2LbNryC',
                'created_at' => '2024-06-24 10:40:54',
                'updated_at' => '2024-06-24 10:40:54',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Wava Littel',
                'email' => 'myrtis.waters@example.net',
                'code' => 'MVTHKRE02E',
                'username' => 'jamil67',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Jqy6Z0hIwLdK6KEnwQQnauCBwATGX7hKOTREIt14pzOs/mAnan2ee',
                'remember_token' => 'tsyKnwX0NZ',
                'created_at' => '2024-06-24 10:40:55',
                'updated_at' => '2024-06-24 10:40:55',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Miss Velda Abbott',
                'email' => 'roy.leffler@example.com',
                'code' => 'OYULLBHPWW',
                'username' => 'wwillms',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Jqy6Z0hIwLdK6KEnwQQnauCBwATGX7hKOTREIt14pzOs/mAnan2ee',
                'remember_token' => 'XhVVAUnqJj',
                'created_at' => '2024-06-24 10:40:55',
                'updated_at' => '2024-06-24 10:40:55',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Jake Gaylord',
                'email' => 'gavin.kessler@example.org',
                'code' => 'YYZXM3EQRK',
                'username' => 'schmitt.blake',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$EhssGiM/4CDeMsJbkEWNGO8ezmmG83a4wCECfmggWKTGOOt6q0aVS',
                'remember_token' => 'NcMA71YkLE',
                'created_at' => '2024-06-24 10:40:55',
                'updated_at' => '2024-06-24 10:40:55',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Anika Huels Sr.',
                'email' => 'tod.mckenzie@example.org',
                'code' => 'KBAT7IAQEY',
                'username' => 'emmerich.dixie',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$EhssGiM/4CDeMsJbkEWNGO8ezmmG83a4wCECfmggWKTGOOt6q0aVS',
                'remember_token' => 'mrQUT040Ak',
                'created_at' => '2024-06-24 10:40:55',
                'updated_at' => '2024-06-24 10:40:55',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Valentin Ziemann DDS',
                'email' => 'lbeahan@example.org',
                'code' => 'XG2VEO89CG',
                'username' => 'beaulah.auer',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$EhssGiM/4CDeMsJbkEWNGO8ezmmG83a4wCECfmggWKTGOOt6q0aVS',
                'remember_token' => 'iWr4T2Mc3F',
                'created_at' => '2024-06-24 10:40:55',
                'updated_at' => '2024-06-24 10:40:55',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Chaz Walker',
                'email' => 'crystel.sporer@example.net',
                'code' => 'QVUVFDTKV0',
                'username' => 'fsmith',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$NVmVh3AhHdsfpz8RtJ3hCOCtsnXPIJ9gFs6/4M31dqirbTTEt3JpW',
                'remember_token' => '1HARO4l7ZC',
                'created_at' => '2024-06-24 10:40:56',
                'updated_at' => '2024-06-24 10:40:56',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Ms. Tess Marks II',
                'email' => 'macejkovic.urban@example.com',
                'code' => 'PZBVRDT9FY',
                'username' => 'heaven09',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$NVmVh3AhHdsfpz8RtJ3hCOCtsnXPIJ9gFs6/4M31dqirbTTEt3JpW',
                'remember_token' => 'q4SGNQbWpj',
                'created_at' => '2024-06-24 10:40:56',
                'updated_at' => '2024-06-24 10:40:56',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Laurel Vandervort',
                'email' => 'mante.marquis@example.org',
                'code' => '8VDX5VRKUV',
                'username' => 'bernita.damore',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$NVmVh3AhHdsfpz8RtJ3hCOCtsnXPIJ9gFs6/4M31dqirbTTEt3JpW',
                'remember_token' => '5e0D9uXcFx',
                'created_at' => '2024-06-24 10:40:56',
                'updated_at' => '2024-06-24 10:40:56',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Khalid Bogan II',
                'email' => 'koepp.cleora@example.org',
                'code' => 'QWR8LVF1CA',
                'username' => 'hahn.brisa',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$x0YOe5aUVsnIUCrHehEZ.uWdJPpnSwi53BzeanLI6Y4l0TvNkHCHq',
                'remember_token' => 's3DlObNd6q',
                'created_at' => '2024-06-24 10:40:56',
                'updated_at' => '2024-06-24 10:40:56',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Judson Cummerata',
                'email' => 'emely69@example.org',
                'code' => 'HUPBCDSAGL',
                'username' => 'iwisoky',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$x0YOe5aUVsnIUCrHehEZ.uWdJPpnSwi53BzeanLI6Y4l0TvNkHCHq',
                'remember_token' => '08i6JJjHap',
                'created_at' => '2024-06-24 10:40:56',
                'updated_at' => '2024-06-24 10:40:56',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Cathy Ondricka',
                'email' => 'willard81@example.com',
                'code' => 'DNKNARVQWY',
                'username' => 'mlarson',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$x0YOe5aUVsnIUCrHehEZ.uWdJPpnSwi53BzeanLI6Y4l0TvNkHCHq',
                'remember_token' => '2iIhlhPAT6',
                'created_at' => '2024-06-24 10:40:56',
                'updated_at' => '2024-06-24 10:40:56',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Dr. Aliyah Ortiz',
                'email' => 'boyer.freda@example.org',
                'code' => 'ORFLZZAEVK',
                'username' => 'kuvalis.lee',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DmUk6AREArGsZrxwPpHTjeZIGgrGff0KlYfBM/WwT2XvI0/oCf1Je',
                'remember_token' => 'TecfbU5hgQ',
                'created_at' => '2024-06-24 10:40:57',
                'updated_at' => '2024-06-24 10:40:57',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Krista Predovic',
                'email' => 'mcglynn.chance@example.org',
                'code' => 'ZW63MNUWBZ',
                'username' => 'ehowe',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DmUk6AREArGsZrxwPpHTjeZIGgrGff0KlYfBM/WwT2XvI0/oCf1Je',
                'remember_token' => 'rvK19uhQC1',
                'created_at' => '2024-06-24 10:40:57',
                'updated_at' => '2024-06-24 10:40:57',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Miss Hosea Hane',
                'email' => 'bennett.adams@example.net',
                'code' => 'UNQZLCUHKV',
                'username' => 'victor.bogisich',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DmUk6AREArGsZrxwPpHTjeZIGgrGff0KlYfBM/WwT2XvI0/oCf1Je',
                'remember_token' => 'bLsZnxojXz',
                'created_at' => '2024-06-24 10:40:57',
                'updated_at' => '2024-06-24 10:40:57',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Dr. Grace Auer',
                'email' => 'porter.kuhic@example.com',
                'code' => '08FSJPUF4F',
                'username' => 'christian.konopelski',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$aJ9Tv79q/wuQVfhLsuPjpunNShYRrhjM1fGnSQ4jYGTmSbk4O1vs2',
                'remember_token' => '6cnBODnF7Z',
                'created_at' => '2024-06-24 10:40:57',
                'updated_at' => '2024-06-24 10:40:57',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Cooper Mayer',
                'email' => 'arvel53@example.com',
                'code' => 'TWMQSB6J7J',
                'username' => 'hester19',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$aJ9Tv79q/wuQVfhLsuPjpunNShYRrhjM1fGnSQ4jYGTmSbk4O1vs2',
                'remember_token' => '88XfAljTfI',
                'created_at' => '2024-06-24 10:40:57',
                'updated_at' => '2024-06-24 10:40:57',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Dangelo Feil IV',
                'email' => 'wbailey@example.com',
                'code' => 'OYI3EN1LGX',
                'username' => 'ispinka',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$aJ9Tv79q/wuQVfhLsuPjpunNShYRrhjM1fGnSQ4jYGTmSbk4O1vs2',
                'remember_token' => 'QOqEaVS4zd',
                'created_at' => '2024-06-24 10:40:57',
                'updated_at' => '2024-06-24 10:40:57',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Gillian Hoppe I',
                'email' => 'lila36@example.com',
                'code' => '6EFD7UADZF',
                'username' => 'wgrimes',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$us3FqSBBcP5tTUq5l0qFYOpRfYOArpmX6D0Jyc6P1XhjqajI590ce',
                'remember_token' => '4xRc6KMFxv',
                'created_at' => '2024-06-24 10:40:58',
                'updated_at' => '2024-06-24 10:40:58',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Christophe Schowalter',
                'email' => 'tressa78@example.org',
                'code' => 'GOSZLKNH1F',
                'username' => 'ted.nienow',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$us3FqSBBcP5tTUq5l0qFYOpRfYOArpmX6D0Jyc6P1XhjqajI590ce',
                'remember_token' => 's4pUSbkA8D',
                'created_at' => '2024-06-24 10:40:58',
                'updated_at' => '2024-06-24 10:40:58',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Albin Hane',
                'email' => 'ukoelpin@example.com',
                'code' => 'GNXEITZJ2J',
                'username' => 'lorenz.gorczany',
                'user_type' => 'student',
                'dob' => NULL,
                'gender' => NULL,
                'photo' => 'http://localhost/global_assets/images/user.png',
                'phone' => NULL,
                'phone2' => NULL,
                'bg_id' => NULL,
                'state_id' => NULL,
                'lga_id' => NULL,
                'nal_id' => NULL,
                'address' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$us3FqSBBcP5tTUq5l0qFYOpRfYOArpmX6D0Jyc6P1XhjqajI590ce',
                'remember_token' => 'jTV8c6eVfD',
                'created_at' => '2024-06-24 10:40:58',
                'updated_at' => '2024-06-24 10:40:58',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Md. Rehema',
                'email' => 'rehema32@gmail.com',
                'code' => 'PRBZUBRVJE',
                'username' => 'MHS/STAFF/2024/06/9446',
                'user_type' => 'teacher',
                'dob' => NULL,
                'gender' => 'Female',
                'photo' => 'http://localhost:8001/global_assets/images/user.png',
                'phone' => '+25411374470',
                'phone2' => '+25411374470',
                'bg_id' => 3,
                'state_id' => 1,
                'lga_id' => 1,
                'nal_id' => 94,
                'address' => 'P.O BOX 18, Muhoroni',
                'email_verified_at' => NULL,
                'password' => '$2y$10$T9mo6FwOG4rByaFxuyFcNO.ROz9XWHxnCwV.3WEG.40jY7Nm98HRu',
                'remember_token' => NULL,
                'created_at' => '2024-06-24 13:30:59',
                'updated_at' => '2024-06-24 13:30:59',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Brian Ngoya',
                'email' => 'ngoyarez@gmail.com',
                'code' => 'IE2ZINEA9Q',
                'username' => 'MHS/S/2024/71988',
                'user_type' => 'student',
                'dob' => '06/18/2002',
                'gender' => 'Male',
                'photo' => 'http://localhost:8001/global_assets/images/user.png',
                'phone' => '+254748883944',
                'phone2' => NULL,
                'bg_id' => 5,
                'state_id' => 2,
                'lga_id' => 18,
                'nal_id' => 94,
                'address' => 'P.O BOX 1699 - 50200, Bungoma',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bbO.0TRdvNvfrAjcThg/7OoVddnHAtrS4Sb8WSfGbEcdoUCRJqrp.',
                'remember_token' => NULL,
                'created_at' => '2024-06-24 13:35:20',
                'updated_at' => '2024-06-24 14:23:53',
            ),
        ));
        
        
    }
}